# SubNav
menu:
  关于我: /aboutme
  友链: /friends
subnav:
  github: "https://github.com/Youthink"
  weibo: "http://weibo.com/u/5263249441"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/hu-yang-11-57/"
  email: "mailto:hufy78@gmail.com"
  youthol: "http://www.youthol.cn"

description: 天马行空，爱生活，爱coding

favicon: /favicon.ico

#你的头像url
avatar: https://tva3.sinaimg.cn/crop.0.0.200.200.180/005Kc3C1jw8f2uep0hhkvj305k05k3yk.jpg

# 展示更新时间
display_updated: true

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: true
